var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(e){return e.raw=e};$jscomp.createTemplateTagFirstArgWithRaw=function(e,l){e.raw=l;return e};$jscomp.arrayIteratorImpl=function(e){var l=0;return function(){return l<e.length?{done:!1,value:e[l++]}:{done:!0}}};$jscomp.arrayIterator=function(e){return{next:$jscomp.arrayIteratorImpl(e)}};$jscomp.makeIterator=function(e){var l="undefined"!=typeof Symbol&&Symbol.iterator&&e[Symbol.iterator];return l?l.call(e):$jscomp.arrayIterator(e)};
$jscomp.arrayFromIterator=function(e){for(var l,p=[];!(l=e.next()).done;)p.push(l.value);return p};$jscomp.arrayFromIterable=function(e){return e instanceof Array?e:$jscomp.arrayFromIterator($jscomp.makeIterator(e))};
(function(){function e(b){return(b=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(b))?[parseInt(b[1],16),parseInt(b[2],16),parseInt(b[3],16)]:null}function l(b){var d=document.createElement("div"),a=document.createElement("div"),f=document.createElement("div"),c=document.createElement("div");d.className="project--parent";a.className="project--title";f.className="project--cell";c.className="project--image";d.appendChild(a);d.appendChild(f);f.appendChild(c);a.innerHTML=b.name.replace(" ","<br>");
a.classList.add("title--white");if(b.image){c.style.backgroundImage="url("+b.image+")";f.style.backgroundColor="rgb(0, 0, 0)";var m=new Image;m.addEventListener("load",function(g){g=document.createElement("canvas").getContext("2d");g.drawImage(m,0,0,1,1);g=g.getImageData(0,0,1,1).data.slice(0,3);f.style.backgroundColor="rgb("+g[0]+", "+g[1]+", "+g[2]+")";125<(299*g[0]+587*g[1]+114*g[2])/1E3&&a.classList.remove("title--white")});m.src=b.image}else{b=D[q];var k=e(b[0]);c.style.backgroundImage="linear-gradient(to right, "+
b[0]+", "+b[1]+")";f.style.backgroundColor="rgb("+k[0]+", "+k[1]+", "+k[2]+")";q=++q>=D.length?0:q}document.querySelector(".projects--wrapper").appendChild(d);E.push(d);-1<J.indexOf(++r)&&r++;d.style.gridRow=~~(r/3+1);d.style.gridColumn=~~(r%3+1)}function p(b,d,a){var f=document.createElement("div"),c=document.createElement("div"),m=document.createElement("div"),k=document.createElement("div"),g=document.createElement("div"),y=document.createElement("div"),z=document.createElement("div"),t=document.createElement("a");
f.className="project--details";c.className="details--content";m.className="details--close";k.className="details--count";g.className="details--title";y.className="details--dev";z.className="details--description";t.className="details--link";k.innerHTML=++a;10>a&&(k.innerHTML="0"+k.innerHTML);g.innerHTML=d.name.replace(" ","<br>");y.innerHTML='<svg><use href="/assets/icons.svg#icon-alert"></use></svg>In development';z.innerHTML=d.descriptions;t.href=d.url;t.innerHTML="View Project";m.innerHTML='<svg><use href="/assets/icons.svg#icon-back"></use></svg>Close';
m.addEventListener("click",A);c.appendChild(k);c.appendChild(g);d.development&&c.appendChild(y);d.descriptions&&c.appendChild(z);d.url&&c.appendChild(t);c.appendChild(m);f.appendChild(c);b.appendChild(f);return f}function K(b){if(!n&&u){b=b.currentTarget;var d=b.parentNode,a=E.indexOf(b);if(-1!=a){u=!1;var f=p(d,F[a],a);a=f.querySelector(".details--content");console.log(a.getBoundingClientRect());a=b.getBoundingClientRect();var c=50*window.innerWidth/100/a.width;c*a.height>.9*window.innerHeight&&(c=.9*window.innerHeight/
a.height);var m=-(a.left+a.width/2-c*a.width/2)+.45*window.innerWidth,k=-(a.top+a.height/2-c*a.height/2)+(window.innerHeight-a.height*c)/2+5;getComputedStyle(document.querySelector("html")).getPropertyValue("--mobile-version")&&(c=.8*window.innerWidth/a.width,m=-(a.left+a.width/2-c*a.width/2)+.1*window.innerWidth,k=-(a.top+a.height/2-c*a.height/2)+.05*window.innerHeight,c*a.height>.5*window.innerHeight&&(c=.5*window.innerHeight/a.height,m=-(a.left+a.width/2-c*a.width/2)+(window.innerWidth-a.width*
c)/2,k=-(a.top+a.height/2-c*a.height/2)+.05*window.innerHeight));d.classList.add("project--is--open");B||window.scroll(0,v);f.style.top=window.pageYOffset+"px";document.body.style.overflow="hidden";b.classList.add("project--open");b.style.zIndex=3;b.querySelector(".project--cell").style.transform="translate3d("+m+"px, "+k+"px, 0) scale3d("+c+", "+c+", 1)";setTimeout(function(g){f.classList.add("show")},50);n=b}}}function A(b){if(n&&!u){u=!0;b&&b.currentTarget&&b.currentTarget.removeEventListener("click",
A);var d=n.parentNode,a=d.querySelector(".project--details");n.querySelector(".project--cell").style.transform="";d.classList.remove("project--is--open");a.classList.remove("show");setTimeout(function(f){document.body.style.overflow="";n.classList.remove("project--open");n.style.zIndex="";d.removeChild(a);n=null},1E3)}}function C(){w&&(document.body.style.height=w.getBoundingClientRect().height+"px")}function G(){v+=Math.floor((window.pageYOffset-v)/10);w.style.transform="translate3d(0, -"+v+"px, 0)";
B||requestAnimationFrame(G)}function L(){h&&h.classList.remove("show");setTimeout(function(){h&&(h.parentNode.removeChild(h),h=null)},300)}function H(){window.removeEventListener("touchstart",H);B=!0;document.body.classList.add("touch")}var F=[{name:"Sift",descriptions:"Online integrated development environment \u2015 create, store and edit files, collaborate with people simultaneously on projects, and also build and run projects in multiple languages from every device you want.",image:"/assets/sift.jpg",
url:"http://sift.ioan.cc"},{name:"Junior Tutorials",descriptions:"Blog and community platform with free access tutorials about general purpose programming languages or graphic APIs such as DirectX or Vulkan.",image:"/assets/tutorial.jpg",url:"https://juniortutorials.xyz"},{name:"smuwnware",descriptions:"Small and fun OS, written in Javascript for browsers. Users can write and register programs using the provided OS functions.",image:"/assets/os.jpg",url:"http://p.ioan.cc/os/",development:!0},{name:"Pina Image",
descriptions:"Minimalist photographer portfolio and events website.",image:"/assets/photo.jpg",url:"https://pinaimage.ro"},{name:"Led Matrix",descriptions:"Display source code and reverse engineered schematic for OKY3525-1 16x16 led matrix and other similar variants.",image:"/assets/matrix.jpg",url:"https://github.com/thirdless/LedMatrix"},{name:"Mazzard",descriptions:"Mini game made in Java as an university project, with 2 levels, in which a prince needs to regain his throne since the monsters have won the whole kingdom. (idk im not the best storywriter)",
image:"/assets/mazzard.png",url:"https://github.com/thirdless/game"},{name:"Crottle",descriptions:"Mini programming e-learning platform, featuring lessons, forum posts and community profiles.",image:"/assets/crottle.jpg",url:"https://github.com/thirdless/crottle"},{name:"Office Clock",descriptions:"Digital office clock, also displaying interior and exterior temperatures, made with RaspberryPi Zero W and a 16x16 Led Matrix Screen.",image:"/assets/clock.png",url:"https://www.hackster.io/macovei/office-clock-using-raspberrypi-b2e295"},
{name:"Hoggins",descriptions:"Customizable first-page, where you can include widgets from reddit and google news posts, to weather widgets and daily themed wallpapers.",image:"/assets/hoggins.jpg",url:"https://p.ioan.cc"},{name:"YouTube Music App",descriptions:"Youtube Music webwrapper with search through playlist functionality, discord integration and more. Since google doesn't want any native desktop app ever.",image:"/assets/youtube.jpg",url:"https://github.com/thirdless/YoutubeMusic"},{name:"Timify",
descriptions:"Easy to use time management javascipt library. From countdowns, clocks and stopwatches, everything is one line away.",image:"/assets/time.jpg",url:"https://github.com/thirdless/timify",development:!0}],D=[["#b92b27","#6a4771"],["#ED8F03","#FFB75E"],["#159957","#155799"]],J=[0,4,8,10,12],I="68 69 40 69 6F 61 6E 2E 63 63".split(" "),q=0,E=[],r=-1,n=null,u=!0,w,v=0,B=!1,h=null,x=null;(function(){h&&h.parentNode.removeChild(h);h=document.createElement("div");h.className="loading--cover show";
document.body.appendChild(h);setTimeout(function(){if(h){var b=document.createElement("div");h.appendChild(b);for(var d=0;4>d;d++)b.appendChild(document.createElement("div"));setTimeout(function(){b.classList.add("show")},50)}},1E3)})();document.addEventListener("DOMContentLoaded",function(){if(w=document.querySelector(".page--root")){F.forEach(function(f){return l(f)});[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".project--parent"))).map(function(f){return f.addEventListener("click",
K)});C();G();for(var b=document.querySelector(".to"),d="",a=0;a<I.length;a++)d+="&#x"+I[a]+";";a=document.createElement("div");a.innerHTML="mailto:"+d;b.setAttribute("href",a.innerHTML);b.innerHTML=d}});window.addEventListener("load",function(){C();L()});window.addEventListener("resize",function(){"number"===typeof x&&clearTimeout(x);A();x=setTimeout(function(){C();x=null},500)});window.addEventListener("touchstart",H)})();

